import { randomBytes } from 'node:crypto';

/**
 * UUIDv7 — a time-ordered UUID (RFC 9562).
 *
 * Time-ordered ids are a deliberate architectural choice (docs/database-design.md §1):
 * they give B-tree index locality on insert-heavy tables (leads, activities, messages),
 * they are not enumerable like serial ints, and they can be generated by the application
 * so a row's id is known before it is written — which the outbox pattern depends on.
 *
 * Layout: 48-bit big-endian unix millisecond timestamp | version 7 | 74 random bits.
 */
export function newId(now: number = Date.now()): string {
  const bytes = randomBytes(16);

  // 48-bit timestamp, most-significant byte first.
  bytes[0] = (now / 0x10000000000) & 0xff;
  bytes[1] = (now / 0x100000000) & 0xff;
  bytes[2] = (now / 0x1000000) & 0xff;
  bytes[3] = (now / 0x10000) & 0xff;
  bytes[4] = (now / 0x100) & 0xff;
  bytes[5] = now & 0xff;

  bytes[6] = (bytes[6]! & 0x0f) | 0x70; // version 7
  bytes[8] = (bytes[8]! & 0x3f) | 0x80; // RFC 9562 variant

  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}

/** Extracts the embedded timestamp from a UUIDv7. Returns null for other versions. */
export function idTimestamp(id: string): Date | null {
  if (!isUuid(id) || id[14] !== '7') return null;
  const hex = id.replace(/-/g, '').slice(0, 12);
  return new Date(Number.parseInt(hex, 16));
}

/** Opaque, URL-safe token for API keys, invitations and webhook secrets. */
export function newToken(byteLength = 32): string {
  return randomBytes(byteLength).toString('base64url');
}
